#!/bin/bash

# hard link files from src dir to tgt dir, assuming flat structure
# useful when there are many files

if [ $# -ne 2 ]; then
    echo >&2 "Usage: $0 src_dir tgt_dir"
    exit 1
fi

SRC="$1"
TGT="$2"

pushd "$TGT" > /dev/null
ABS_TGT="$PWD"
popd > /dev/null

cd "$SRC"
find . -type d -exec mkdir -p "$ABS_TGT"/{} \;
find . -type f -exec ln {} "$ABS_TGT"/{} \;
